import Head from "next/head";
import SingleTreatment from "../../components/SingleTreatment";

export default function SingleTreatmentPage({ query }) {
  return (
    <div>
      <Head>
        <title>Enga Beauty | {query.name}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="mt-10 lg:mt-44">
        <SingleTreatment id={query.id} />;
      </div>
    </div>
  );
}
