import Head from "next/head";
import Image from "next/image";
import HandpleieDame from "../../components/TreatmentsAndPrices/Handpleie/HandpleieDame";
import HandpleieHerre from "../../components/TreatmentsAndPrices/Handpleie/HandpleieHerre";

export default function FotpleiePage() {
  return (
    <div>
      <Head>
        <title>Enga Beauty | Håndpleie</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="my-32 flex flex-col items-center font-quicksand">
        <div className="mt-10 w-1/2">
          <h2 className="ml-6 mb-4 flex text-2xl font-semibold tracking-wide text-gray-600 md:mx-10 lg:ml-0 lg:justify-center">
            Håndpleie
          </h2>
          <div className="mb-2">
            <Image
              className="object-cover"
              src="/images/pics/Hands2.jpg"
              width={1000}
              height={600}
            />
          </div>
          <div className="bg-[#FCFAFA] pt-1 pb-4 lg:px-2 lg:pt-4">
            <h3 className="ml-6 mb-6 flex text-xl font-medium md:mx-10 lg:ml-2">
              Håndpleie Dame
            </h3>
            <HandpleieDame />
            <h3 className="ml-6 mt-12 mb-6 flex text-xl font-medium md:mx-10 lg:ml-2">
              Håndpleie Herre
            </h3>
            <HandpleieHerre />
          </div>
        </div>
      </div>
    </div>
  );
}
