import Head from "next/head";
import Image from "next/image";
import Microblading from "../../components/TreatmentsAndPrices/Microblading/Microblading";

export default function MicrobladingPage() {
  return (
    <div>
      <Head>
        <title>Enga Beauty | Microblading</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="my-32 flex flex-col items-center font-quicksand">
        <div className="mt-10 w-1/2">
          <h2 className="ml-6 mb-4 flex text-2xl font-semibold tracking-wide text-gray-600 md:mx-10 lg:ml-0 lg:justify-center">
            Microblading
          </h2>
          <div className="mb-2">
            <Image
              className="object-cover"
              src="/images/pics/microblading.jpg"
              width={1000}
              height={600}
            />
          </div>
          <div className="bg-[#FCFAFA] pt-1 pb-4 lg:px-2 lg:pt-4">
            <Microblading />
          </div>
        </div>
      </div>
    </div>
  );
}
