import Image from "next/image";
import Vippe from "../../components/TreatmentsAndPrices/VipperOgBryn/Vippe";
import Bryn from "../../components/TreatmentsAndPrices/VipperOgBryn/Bryn";
import Head from "next/head";

export default function VipperOgBrynPage() {
  return (
    <div>
      <Head>
        <title>Enga Beauty | Vipper og Bryn</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="my-32 flex flex-col items-center font-quicksand">
        <div className="mt-10 w-1/2">
          <h2 className="ml-6 mb-4 flex text-2xl font-semibold tracking-wide text-gray-600 md:mx-10 lg:ml-0 lg:justify-center">
            Vipper og Bryn
          </h2>
          <div className="mb-2">
            <Image
              className="object-cover"
              src="/images/pics/brows-lashes.jpg"
              width={1000}
              height={600}
            />
          </div>
          <div className="bg-[#FCFAFA] pt-1 pb-4 lg:px-2 lg:pt-4">
            <h3 className="ml-6 mb-6 flex text-xl font-medium md:mx-10 lg:ml-2">
              Vippe
            </h3>
            <Vippe />
            <h3 className="ml-6 mb-6 mt-12 flex text-xl font-medium md:mx-10 lg:ml-2">
              Brynsløft
            </h3>
            <Bryn />
          </div>
        </div>
      </div>
    </div>
  );
}
