import Head from "next/head";
import Treatments from "../../components/Treatment/Treatments";

export default function TreatmentsPage() {
  return (
    <div>
      <Head>
        <title>Enga Beauty | Treatments & Prices</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="mt-44">
        <Treatments />
      </div>
    </div>
  );
}
