import tw, { styled } from "twin.macro";
import "styled-components/macro";
import ShoppingBag from "../components/ShoppingBag/ShoppingBag";
import Head from "next/head";

export default function ShoppingBagPage() {
  return (
    <div>
      <Head>
        <title>Enga Beauty</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div tw="mt-40 items-center flex justify-center">
        <ShoppingBag />
      </div>
    </div>
  );
}
